# 1. Carga del Dataset FIFA Ranking.

Este dataset contiene la evolución histórica del ranking FIFA de las selecciones nacionales.

Su objetivo dentro del proyecto será proporcionar una medida de la fuerza relativa de cada selección en distintos momentos del tiempo.

In [1]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fifa = pd.read_csv("../data/raw/fifa_ranking_2026.csv")

# 2. Inspección Inicial del Dataset

Mirar:
- Nº de filas.
- Nº de columnas.
- Tipos de datos.
- Estructura.

In [4]:
fifa

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.00,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.00,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.00,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.00,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.00,30,CAF,1992-12-31
...,...,...,...,...,...,...,...,...,...
70189,70189,229.0,Brunei Darussalam,BRU,633.0,875.78,-41,AFC,2026-04-01
70190,70190,231.0,US Virgin Islands,VIR,627.0,776.60,-24,CONCACAF,2026-04-01
70191,70191,232.0,Cook Islands,COK,622.0,877.53,-46,OFC,2026-04-01
70192,70192,233.0,Macau,MAC,589.0,865.29,-40,AFC,2026-04-01
70193,70193,239.0,Tonga,TGA,520.0,835.64,-42,OFC,2026-04-01

In [5]:
fifa.shape

(70194, 9)

In [6]:
fifa.head()

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

In [7]:
fifa.info()

<class 'pandas.DataFrame'>
RangeIndex: 70194 entries, 0 to 70193
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       70194 non-null  int64
 1   rank             70185 non-null  float64
 2   country_full     70194 non-null  str
 3   country_abrv     70194 non-null  str
 4   total_points     70194 non-null  float64
 5   previous_points  70194 non-null  float64
 6   rank_change      70194 non-null  int64
 7   confederation    70194 non-null  str
 8   rank_date        70194 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 6.6 MB

In [8]:
fifa.columns

Index(['Unnamed: 0', 'rank', 'country_full', 'country_abrv', 'total_points',
       'previous_points', 'rank_change', 'confederation', 'rank_date'],
      dtype='str')

# 3. Detección de valores nulos

Se analiza la presencia de valores faltantes para determinar si es necesario realizar imputaciones o eliminar registros.

In [9]:
fifa.isnull().sum()

Unnamed: 0         0
rank               9
country_full       0
country_abrv       0
total_points       0
previous_points    0
rank_change        0
confederation      0
rank_date          0
dtype: int64

In [14]:
fifa = fifa.dropna(
    subset=["rank"]
)

# 4. Análisis de Duplicados

In [15]:
fifa.duplicated().sum()

np.int64(0)

# 5. Eliminación de columnas irrelevantes

El dataset contiene algunas variables que no aportarán información relevante al modelo predictivo o que generan información redundante.

Se eliminan aquellas columnas que no serán utilizadas durante la fase de modelado.

In [16]:
fifa = fifa.drop(
    columns=["Unnamed: 0"]
)

KeyError: "['Unnamed: 0'] not found in axis"

# 5. Conversión de Variables Temporales

La variable rank_date se convierte al formato datetime para facilitar futuras operaciones temporales y la integración con los resultados históricos de los partidos.

In [17]:
fifa["rank_date"] = pd.to_datetime(
    fifa["rank_date"]
)

In [18]:
fifa.info()

<class 'pandas.DataFrame'>
Index: 70185 entries, 0 to 70193
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             70185 non-null  float64
 1   country_full     70185 non-null  str
 2   country_abrv     70185 non-null  str
 3   total_points     70185 non-null  float64
 4   previous_points  70185 non-null  float64
 5   rank_change      70185 non-null  int64
 6   confederation    70185 non-null  str
 7   rank_date        70185 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 5.9 MB

# 6. Análisis temporal del ranking FIFA

In [19]:
fifa["rank_date"].min()

Timestamp('1992-12-31 00:00:00')

In [20]:
fifa["rank_date"].max()

Timestamp('2026-04-01 00:00:00')

# 7. Revisar selecciones

In [21]:
fifa["country_full"].nunique()

216

In [22]:
sorted(
    fifa["country_full"].unique()
)

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China PR',
 'Chinese Taipei',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo DR',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 'Czechoslovakia',
 "Côte d'Ivoire",
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong, China',
 'Hungary',
 'IR Iran',
 'Iceland',
 'India',
 'Indonesia',
 'Iraq',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Korea DPR',
 'Korea Republic',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Northern Ireland',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St Kitts and Nevis',
 'St Lucia',
 'St Vincent and the Grenadines',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Tahiti',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'The Gambia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Türkiye',
 'US Virgin Islands',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Wales',
 'Yemen',
 'Yugoslavia',
 'Zaire',
 'Zambia',
 'Zimbabwe']

# 9. Dataset final FIFA

In [23]:
fifa = fifa[
    [
        "rank_date",
        "country_full",
        "rank",
        "total_points"
    ]
]

In [25]:
fifa = fifa[
    (fifa["rank_date"] >= "2000-01-01") &
    (fifa["rank_date"] <= "2025-12-31")
]

In [26]:
fifa["rank_date"].min()

Timestamp('2000-01-19 00:00:00')

In [27]:
fifa["rank_date"].max()

Timestamp('2025-12-19 00:00:00')

In [28]:
fifa.shape

(57203, 4)

In [29]:
fifa.to_csv(
    "fifa_final.csv",
    index=False
)