# 1. Carga del dataset Elo

Se carga el dataset histórico de Elo Ratings que será utilizado posteriormente para enriquecer los partidos con información de fuerza relativa de las selecciones.

In [1]:
import pandas as pd
import numpy as np

elo = pd.read_csv("data/eloratings.csv")

# 2. Inspección inicial del dataset

In [2]:
elo.head()

         date      team  rating  change
0  1872-11-30   England  2003.0       3
1  1872-11-30  Scotland  1997.0      -3
2  1873-03-08   England  2014.0      11
3  1873-03-08  Scotland  1986.0     -11
4  1874-03-07   England  2006.0      -8

In [11]:
elo.info()

<class 'pandas.DataFrame'>
Index: 6647 entries, 0 to 6677
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6647 non-null   str
 1   team    6647 non-null   str
 2   rating  6647 non-null   float64
 3   change  6647 non-null   int64
dtypes: float64(1), int64(1), str(2)
memory usage: 375.3 KB

In [12]:
elo["date"].head(20)

0     1872-11-30
1     1872-11-30
2     1873-03-08
3     1873-03-08
4     1874-03-07
5     1874-03-07
6     1875-03-06
7     1875-03-06
8     1876-03-04
9     1876-03-04
10    1876-03-25
11    1876-03-25
12    1882-02-25
13    1882-02-25
14    1883-02-24
15    1883-02-24
16    1884-02-23
17    1884-02-23
18    1885-04-11
19    1885-04-11
Name: date, dtype: str

In [13]:
elo["date"].tail(20)

6658    12/13/2025
6659    12/13/2025
6660    12/13/2025
6661    12/13/2025
6662    12/13/2025
6663    12/13/2025
6664    12/13/2025
6665    12/13/2025
6666    12/13/2025
6667    12/13/2025
6668    12/13/2025
6669    12/13/2025
6670    12/13/2025
6671    12/13/2025
6672    12/13/2025
6673    12/13/2025
6674    12/13/2025
6675    12/13/2025
6676    12/13/2025
6677    12/13/2025
Name: date, dtype: str

In [4]:
elo.shape

(6678, 4)

# 3. Análisis de valores nulos

In [5]:
elo.isnull().sum()

date       0
team       0
rating    31
change     0
dtype: int64

In [6]:
elo = elo.dropna()

In [7]:
elo.isnull().sum()

date      0
team      0
rating    0
change    0
dtype: int64

# 5. Análisis de duplicados

In [8]:
elo.duplicated().sum()

np.int64(0)

# 6. Conversión de variables temporales

In [14]:
elo["date"] = pd.to_datetime(
    elo["date"],
    format="mixed"
)

# 7. Análisis temporal

In [15]:
elo["date"].min()

Timestamp('1872-11-30 00:00:00')

In [16]:
elo["date"].max()

Timestamp('2025-12-13 00:00:00')

# 8. Filtrado temporal definitivo

Se conservan únicamente los registros comprendidos entre los años 2000 y 2025 para mantener coherencia temporal con el resto de datasets utilizados en el proyecto.

In [17]:
elo = elo[
    (elo["date"] >= "2000-01-01") &
    (elo["date"] <= "2025-12-31")
]

In [18]:
elo["date"].min()

Timestamp('2000-03-19 00:00:00')

In [19]:
elo["date"].max()

Timestamp('2025-12-13 00:00:00')

In [20]:
elo.shape

(5073, 4)

# 9. Selección de variables finales

In [21]:
elo_clean = elo[
    [
        "date",
        "team",
        "rating"
    ]
]

In [22]:
elo_clean.info()

<class 'pandas.DataFrame'>
Index: 5073 entries, 1577 to 6677
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5073 non-null   datetime64[us]
 1   team    5073 non-null   str
 2   rating  5073 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 201.4 KB

# 10. Análisis de selecciones

In [23]:
elo_clean["team"].nunique()

248

In [24]:
sorted(
    elo_clean["team"].unique()
)

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua\xa0and\xa0Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire',
 'Bosnia\xa0and\xa0Herzegovina',
 'Botswana',
 'Brazil',
 'British\xa0Virgin\xa0Islands',
 'Brunei',
 'Bulgaria',
 'Burkina\xa0Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape\xa0Verde',
 'Cayman\xa0Islands',
 'Central\xa0African\xa0Republic',
 'Chad',
 'Chagos\xa0Islands',
 'Chile',
 'China',
 'Christmas\xa0Island',
 'Cocos\xa0Islands',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook\xa0Islands',
 'Costa\xa0Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 'Democratic\xa0Republic\xa0of\xa0Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican\xa0Republic',
 'Eastern\xa0Samoa',
 'East\xa0Timor',
 'Ecuador',
 'Egypt',
 'El\xa0Salvador',
 'England',
 'Equatorial\xa0Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland\xa0Islands',
 'Faroe\xa0Islands',
 'Federated\xa0States\xa0of\xa0Micronesia',
 'Fiji',
 'Finland',
 'France',
 'French\xa0Guiana',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong\xa0Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory\xa0Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kurdistan',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall\xa0Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New\xa0Caledonia',
 'New\xa0Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Northern\xa0Cyprus',
 'Northern\xa0Ireland',
 'Northern\xa0Mariana\xa0Islands',
 'North\xa0Korea',
 'North\xa0Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua\xa0New\xa0Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto\xa0Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saba',
 'Saint\xa0Barthelemy',
 'Saint\xa0Kitts\xa0and\xa0Nevis',
 'Saint\xa0Lucia',
 'Saint\xa0Martin',
 'Saint\xa0Pierre\xa0and\xa0Miquelon',
 'Saint\xa0Vincent\xa0and\xa0the\xa0Grenadines',
 'Samoa',
 'San\xa0Marino',
 'Sao\xa0Tome\xa0and\xa0Principe',
 'Saudi\xa0Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Serbia\xa0and\xa0Montenegro',
 'Seychelles',
 'Sierra\xa0Leone',
 'Singapore',
 'Sint\xa0Eustatius',
 'Sint\xa0Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon\xa0Islands',
 'Somalia',
 'Somaliland',
 'South\xa0Africa',
 'South\xa0Korea',
 'South\xa0Sudan',
 'Spain',
 'Sri\xa0Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Tibet',
 'Togo',
 'Tonga',
 'Trinidad\xa0and\xa0Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks\xa0and\xa0Caicos\xa0Islands',
 'Tuvalu',
 'US\xa0Virgin\xa0Islands',
 'Uganda',
 'Ukraine',
 'United\xa0Arab\xa0Emirates',
 'United\xa0States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Wales',
 'Wallis\xa0and\xa0Futuna',
 'Western\xa0Sahara',
 'Yemen',
 'Yugoslavia',
 'Zambia',
 'Zanzibar',
 'Zimbabwe']

# 11. Dataset final

In [25]:
elo_clean.shape

(5073, 3)

In [26]:
elo_clean.head()

           date       team  rating
1577 2000-03-19  Guatemala  1527.0
1578 2000-03-19       Cuba  1506.0
1579 2000-03-19      Haiti  1441.0
1580 2000-03-19     Panama  1384.0
1581 2000-03-19    Bermuda  1308.0

In [27]:
elo_clean.to_csv(
    "data/elo_final.csv",
    index=False
)