In [1]:
import pandas as pd

import pandas as pd # linear algebra

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
prueba_elo = pd.read_csv("data/eloratings.csv")

In [3]:
prueba_elo

            date                      team  rating  change
0     1872-11-30                   England  2003.0       3
1     1872-11-30                  Scotland  1997.0      -3
2     1873-03-08                   England  2014.0      11
3     1873-03-08                  Scotland  1986.0     -11
4     1874-03-07                   England  2006.0      -8
...          ...                       ...     ...     ...
6673  12/13/2025  Northern Mariana Islands   432.0       0
6674  12/13/2025             Cocos Islands   422.0       0
6675  12/13/2025                     Palau   402.0       0
6676  12/13/2025             Eastern Samoa   389.0       0
6677  12/13/2025                   Moldova     0.0       0

[6678 rows x 4 columns]

In [4]:
prueba_elo.info()

<class 'pandas.DataFrame'>
RangeIndex: 6678 entries, 0 to 6677
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6678 non-null   str
 1   team    6678 non-null   str
 2   rating  6647 non-null   float64
 3   change  6678 non-null   int64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 KB

Cargp el dataset de results

In [44]:
df_resultado = pd.read_csv("data/results.csv")
df_resultado

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

Se visualizan las diferentes columnas

In [45]:
print(df_resultado.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

Me quedo con las columnas que me interesan

In [46]:
df_matches = df_resultado[
    [
        "date",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "tournament",
        "neutral"
    ]
].copy()

In [47]:
df_matches

,date,home_team,away_team,home_score,away_score,tournament,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,False
...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,True
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,True
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,True
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,True

convertir la fecha

In [48]:
df_matches["date"] = pd.to_datetime(df_matches["date"])

revisar el resultado

In [49]:
print(df_matches.head())
print(df_matches.shape)

        date home_team away_team  home_score  away_score tournament  neutral
0 1872-11-30  Scotland   England         0.0         0.0   Friendly    False
1 1873-03-08   England  Scotland         4.0         2.0   Friendly    False
2 1874-03-07  Scotland   England         2.0         1.0   Friendly    False
3 1875-03-06   England  Scotland         2.0         2.0   Friendly    False
4 1876-03-04  Scotland   England         3.0         0.0   Friendly    False
(49287, 7)

crear los targets

In [50]:
df_matches["target_home_goals"] = df_matches["home_score"]
df_matches["target_away_goals"] = df_matches["away_score"]

In [51]:
print(df_matches.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'neutral', 'target_home_goals', 'target_away_goals'],
      dtype='str')

Vemos los valores nulos

In [52]:
df_matches.info()
df_matches.head()

<class 'pandas.DataFrame'>
RangeIndex: 49287 entries, 0 to 49286
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               49287 non-null  datetime64[us]
 1   home_team          49287 non-null  str
 2   away_team          49287 non-null  str
 3   home_score         49215 non-null  float64
 4   away_score         49215 non-null  float64
 5   tournament         49287 non-null  str
 6   neutral            49287 non-null  bool
 7   target_home_goals  49215 non-null  float64
 8   target_away_goals  49215 non-null  float64
dtypes: bool(1), datetime64[us](1), float64(4), str(3)
memory usage: 3.1 MB

,date,home_team,away_team,home_score,away_score,tournament,neutral,target_home_goals,target_away_goals
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,False,0.0,0.0
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,False,4.0,2.0
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,False,2.0,1.0
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,False,2.0,2.0
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,False,3.0,0.0

Eliminamos los 72 partidos sin resultados

In [53]:
df_matches = df_matches.dropna(
    subset=["home_score", "away_score"]
)

In [54]:
df_matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 49215 entries, 0 to 49214
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               49215 non-null  datetime64[us]
 1   home_team          49215 non-null  str
 2   away_team          49215 non-null  str
 3   home_score         49215 non-null  float64
 4   away_score         49215 non-null  float64
 5   tournament         49215 non-null  str
 6   neutral            49215 non-null  bool
 7   target_home_goals  49215 non-null  float64
 8   target_away_goals  49215 non-null  float64
dtypes: bool(1), datetime64[us](1), float64(4), str(3)
memory usage: 3.1 MB

Cargo el ranking FIFA

In [55]:
ranking_fifa= pd.read_csv("data/fifa_ranking-2026-04-01.csv")

In [56]:
ranking_fifa.info()

<class 'pandas.DataFrame'>
RangeIndex: 70194 entries, 0 to 70193
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       70194 non-null  int64
 1   rank             70185 non-null  float64
 2   country_full     70194 non-null  str
 3   country_abrv     70194 non-null  str
 4   total_points     70194 non-null  float64
 5   previous_points  70194 non-null  float64
 6   rank_change      70194 non-null  int64
 7   confederation    70194 non-null  str
 8   rank_date        70194 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 4.8 MB

In [57]:
ranking_fifa.head()

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

In [58]:
ranking_fifa.columns

Index(['Unnamed: 0', 'rank', 'country_full', 'country_abrv', 'total_points',
       'previous_points', 'rank_change', 'confederation', 'rank_date'],
      dtype='str')

In [59]:
ranking_fifa = ranking_fifa.drop(columns=["Unnamed: 0"])

Convertir la fecha

In [60]:
ranking_fifa["rank_date"] = pd.to_datetime(
    ranking_fifa["rank_date"]
)

In [61]:
ranking_fifa.info()

<class 'pandas.DataFrame'>
RangeIndex: 70194 entries, 0 to 70193
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             70185 non-null  float64
 1   country_full     70194 non-null  str
 2   country_abrv     70194 non-null  str
 3   total_points     70194 non-null  float64
 4   previous_points  70194 non-null  float64
 5   rank_change      70194 non-null  int64
 6   confederation    70194 non-null  str
 7   rank_date        70194 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 4.3 MB

se necesita saber si los nombres de países coinciden.

In [62]:
print(df_matches["home_team"].nunique())
print(ranking_fifa["country_full"].nunique())

325
216

In [63]:
set(df_matches["home_team"]).difference(
    set(ranking_fifa["country_full"])
)

{'Abkhazia',
 'Alderney',
 'Andalusia',
 'Arameans Suryoye',
 'Artsakh',
 'Aymara',
 'Barawa',
 'Basque Country',
 'Biafra',
 'Bonaire',
 'Brittany',
 'Brunei',
 'Canary Islands',
 'Cape Verde',
 'Cascadia',
 'Catalonia',
 'Central Spain',
 'Chagos Islands',
 'Chameria',
 'Chechnya',
 'Corsica',
 'County of Nice',
 'Czech Republic',
 'DR Congo',
 'Darfur',
 'Donetsk PR',
 'Délvidék',
 'Elba Island',
 'Ellan Vannin',
 'Falkland Islands',
 'Felvidék',
 'Franconia',
 'French Guiana',
 'Frøya',
 'Galicia',
 'Gambia',
 'German DR',
 'Gotland',
 'Gozo',
 'Greenland',
 'Guadeloupe',
 'Guernsey',
 'Găgăuzia',
 'Hitra',
 'Hmong',
 'Hong Kong',
 'Iran',
 'Iraqi Kurdistan',
 'Isle of Man',
 'Isle of Wight',
 'Ivory Coast',
 'Jersey',
 'Kabylia',
 'Kernow',
 'Kiribati',
 'Kyrgyzstan',
 'Kárpátalja',
 'Luhansk PR',
 'Madrid',
 'Manchukuo',
 'Mapuche',
 'Marshall Islands',
 'Martinique',
 'Matabeleland',
 'Mayotte',
 'Menorca',
 'Micronesia',
 'Monaco',
 'Niue',
 'North Korea',
 'North Vietnam',
 'Northern Cyprus',
 'Northern Mariana Islands',
 'Occitania',
 'Orkney',
 'Padania',
 'Palau',
 'Panjab',
 'Parishes of Jersey',
 'Provence',
 'Raetia',
 'Republic of St. Pauli',
 'Rhodes',
 'Romani people',
 'Ryūkyū',
 'Réunion',
 'Saare County',
 'Saarland',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Sark',
 'Saugeais',
 'Sealand',
 'Seborga',
 'Shetland',
 'Silesia',
 'Sint Maarten',
 'Somaliland',
 'South Korea',
 'South Ossetia',
 'Székely Land',
 'Sápmi',
 'Taiwan',
 'Tamil Eelam',
 'Tibet',
 'Ticino',
 'Turkey',
 'Tuvalu',
 'United Koreans in Japan',
 'United States',
 'United States Virgin Islands',
 'Vatican City',
 'Vietnam Republic',
 'Wallis Islands and Futuna',
 'West Papua',
 'Western Armenia',
 'Western Australia',
 'Western Isles',
 'Western Sahara',
 'Yemen DPR',
 'Ynys Môn',
 'Yorkshire',
 'Yoruba Nation',
 'Zanzibar',
 'Åland Islands'}

In [64]:
list(
    set(df_matches["home_team"]).difference(
        set(ranking_fifa["country_full"])
    )
)[:20]

['Northern Cyprus',
 'Martinique',
 'Ivory Coast',
 'Saugeais',
 'Western Isles',
 'Czech Republic',
 'Ynys Môn',
 'Central Spain',
 'Iran',
 'Romani people',
 'Isle of Wight',
 'Silesia',
 'Sápmi',
 'Chechnya',
 'Gotland',
 'Sark',
 'Hitra',
 'Saint Pierre and Miquelon',
 'Galicia',
 'Monaco']

Me quedo con los paises ya que aparecen algunas selecciones Autonómicas como Galicia o Andalucía

In [65]:
fifa_countries = set(ranking_fifa["country_full"])

df_matches = df_matches[
    df_matches["home_team"].isin(fifa_countries)
]

df_matches = df_matches[
    df_matches["away_team"].isin(fifa_countries)
]

In [66]:
df_matches.shape

(39491, 9)

In [67]:
df_matches = df_matches[
    df_matches["date"] >= "1993-01-01"
]

In [68]:
df_matches.shape

(24289, 9)

In [69]:
print(df_matches.shape)

print(df_matches["date"].min())

print(df_matches["date"].max())

(24289, 9)
1993-01-01 00:00:00
2026-03-31 00:00:00

In [70]:
print(df_matches["home_team"].sample(20).tolist())

['Ethiopia', 'Chad', 'Lithuania', 'Netherlands', 'Cyprus', 'Uzbekistan', 'Nicaragua', 'Nigeria', 'Latvia', 'Egypt', 'Morocco', 'Finland', 'Tahiti', 'New Zealand', 'El Salvador', 'Vanuatu', 'Burkina Faso', 'Slovenia', 'Kazakhstan', 'Guyana']

In [71]:
print(
    ranking_fifa["country_full"]
    .sample(20)
    .tolist()
)

['Guam', 'Malta', 'Uganda', 'Suriname', 'United Arab Emirates', 'Lithuania', 'The Gambia', 'Mauritania', 'St Lucia', 'Scotland', 'Brazil', 'Malaysia', 'Slovakia', 'Hong Kong, China', 'Mongolia', 'New Zealand', 'Ghana', 'Liechtenstein', 'Hungary', 'Thailand']

In [72]:
ranking_fifa["rank_date"].nunique()

346

In [73]:
ranking_fifa["rank_date"].min(),
ranking_fifa["rank_date"].max()

Timestamp('2026-04-01 00:00:00')

Se revisa la coincidencia de los nombre para no encontrar USA y unite State

In [74]:
common_teams = set(df_matches["home_team"]).intersection(
    set(ranking_fifa["country_full"])
)

print("Coinciden:", len(common_teams))

print("Equipos partidos:", df_matches["home_team"].nunique())

print("Equipos FIFA:", ranking_fifa["country_full"].nunique())

Coinciden: 194
Equipos partidos: 194
Equipos FIFA: 216

In [75]:
missing = sorted(
    set(df_matches["home_team"]) -
    set(ranking_fifa["country_full"])
)

print(missing[:100])

[]

In [76]:
print(ranking_fifa["rank_date"].min())
print(ranking_fifa["rank_date"].max())

1992-12-31 00:00:00
2026-04-01 00:00:00

Me quedo con las columnas necesarias

In [77]:
fifa = ranking_fifa[
    [
        "country_full",
        "rank_date",
        "rank",
        "total_points"
    ]
].copy()

ordenar fechas

In [78]:
fifa = fifa.sort_values("rank_date")

df_ml = df_matches.sort_values("date")

In [79]:
home_fifa = fifa.rename(
    columns={
        "country_full": "home_team",
        "rank": "fifa_rank_home",
        "total_points": "fifa_points_home",
        "rank_date": "date"
    }
)

In [80]:
df_ml = pd.merge_asof(
    df_ml.sort_values("date"),
    home_fifa.sort_values("date"),
    on="date",
    by="home_team",
    direction="backward"
)

In [81]:
df_ml[
    [
        "home_team",
        "date",
        "fifa_rank_home",
        "fifa_points_home"
    ]
].head()

      home_team       date  fifa_rank_home  fifa_points_home
0         Ghana 1993-01-01            39.0              34.0
1         Gabon 1993-01-02            55.0              27.0
2        Kuwait 1993-01-02            71.0              21.0
3  Burkina Faso 1993-01-03            97.0              11.0
4         Gabon 1993-01-03            55.0              27.0

In [82]:
away_fifa = fifa.rename(
    columns={
        "country_full": "away_team",
        "rank": "fifa_rank_away",
        "total_points": "fifa_points_away",
        "rank_date": "date"
    }
)

In [83]:
df_ml = pd.merge_asof(
    df_ml.sort_values("date"),
    away_fifa.sort_values("date"),
    on="date",
    by="away_team",
    direction="backward"
)

In [84]:
df_ml[
    [
        "home_team",
        "away_team",
        "fifa_rank_home",
        "fifa_rank_away",
        "fifa_points_home",
        "fifa_points_away"
    ]
].head()

,home_team,away_team,fifa_rank_home,fifa_rank_away,fifa_points_home,fifa_points_away
0,Ghana,Mali,39.0,69.0,34.0,22.0
1,Gabon,Burkina Faso,55.0,97.0,27.0,11.0
2,Kuwait,Lebanon,71.0,161.0,21.0,0.0
3,Burkina Faso,Mali,97.0,69.0,11.0,22.0
4,Gabon,Ghana,55.0,39.0,27.0,34.0

In [85]:
df_ml["rank_diff"] = (
    df_ml["fifa_rank_home"]
    - df_ml["fifa_rank_away"]
)

df_ml["points_diff"] = (
    df_ml["fifa_points_home"]
    - df_ml["fifa_points_away"]
)

In [86]:
print(df_ml.isna().sum())

date                   0
home_team              0
away_team              0
home_score             0
away_score             0
tournament             0
neutral                0
target_home_goals      0
target_away_goals      0
fifa_rank_home       170
fifa_points_home     168
fifa_rank_away       259
fifa_points_away     254
rank_diff            402
points_diff          396
dtype: int64

In [87]:
print(
    df_ml[
        [
            "fifa_rank_home",
            "fifa_rank_away"
        ]
    ].isna().sum()
)

fifa_rank_home    170
fifa_rank_away    259
dtype: int64

In [88]:
df_ml.shape

df_ml.head()

df_ml[
    [
        "fifa_rank_home",
        "fifa_rank_away"
    ]
].isna().sum()

fifa_rank_home    170
fifa_rank_away    259
dtype: int64

In [89]:
df_ml[
    df_ml["fifa_rank_home"].isna()
][
    ["date","home_team","away_team"]
].head(20)

          date       home_team             away_team
106 1993-03-12  Cayman Islands              Barbados
124 1993-03-30        Slovakia             Lithuania
136 1993-04-04        Anguilla   Antigua and Barbuda
142 1993-04-08       Sri Lanka  United Arab Emirates
164 1993-04-13       Sri Lanka            Bangladesh
166 1993-04-13         Vietnam             Singapore
180 1993-04-16         Vietnam             Indonesia
209 1993-04-26         Vietnam                 Qatar
227 1993-05-01           Macau          Saudi Arabia
234 1993-05-03           Macau                Kuwait
236 1993-05-03       Sri Lanka              Thailand
241 1993-05-05       Sri Lanka                 Japan
260 1993-05-18           Macau              Malaysia
262 1993-05-18        Mongolia                 Macau
279 1993-05-25      Azerbaijan               Georgia
301 1993-06-02    Turkmenistan            Tajikistan
308 1993-06-06      Azerbaijan            Tajikistan
324 1993-06-11         Vietnam           Philippines
555 1993-11-16        Slovakia              Slovenia
586 1993-12-08   New Caledonia      Papua New Guinea

In [90]:
df_ml[
    df_ml["fifa_rank_away"].isna()
][
    ["date","home_team","away_team"]
].head(20)

          date             home_team               away_team
101 1993-03-11                Guyana          Cayman Islands
109 1993-03-14           Puerto Rico          Cayman Islands
138 1993-04-04    Dominican Republic  British Virgin Islands
153 1993-04-11              Thailand               Sri Lanka
156 1993-04-11                 Qatar                 Vietnam
176 1993-04-15                 Japan               Sri Lanka
208 1993-04-25               Grenada                Dominica
212 1993-04-28  United Arab Emirates               Sri Lanka
215 1993-04-28             Singapore                 Vietnam
224 1993-04-30             Indonesia                 Vietnam
240 1993-05-05              Malaysia                   Macau
244 1993-05-07            Bangladesh               Sri Lanka
247 1993-05-10              China PR                Mongolia
250 1993-05-12              China PR                   Macau
253 1993-05-14          Saudi Arabia                   Macau
257 1993-05-16                Kuwait                   Macau
262 1993-05-18              Mongolia                   Macau
279 1993-05-25            Azerbaijan                 Georgia
301 1993-06-02          Turkmenistan              Tajikistan
308 1993-06-06            Azerbaijan              Tajikistan

# OTRA COSAA